Creates Login & Registration screen
lauyoo46/ProjectICP pull request #1
Opened 2021-02-11 12:42 UTC by lauyoo46

![Screenshot 2021-02-11 at 14 40 56](https://user-images.githubusercontent.com/38860865/107637743-4c2f2c00-6c77-11eb-99e4-ecfa8efefc22.png)
![Screenshot 2021-02-11 at 14 41 02](https://user-images.githubusercontent.com/38860865/107637746-4d605900-6c77-11eb-8ca7-2331f62cd8c5.png)
![Screenshot 2021-02-11 at 14 41 10](https://user-images.githubusercontent.com/38860865/107637751-4e918600-6c77-11eb-829a-deb704627279.png)
![Screenshot 2021-02-11 at 14 41 47](https://user-images.githubusercontent.com/38860865/107637757-50f3e000-6c77-11eb-8bcd-1b24158960fc.png)

2021-02-15 11:19 UTC, czegreanu requested changes

2021-02-15 11:19 UTC, czegreanu commented on Incopo/AppDelegate.swift
> +        let container = NSPersistentContainer(name: "Incopo".localized)
don't localize this, can cause problems when switching language. it's not displayed on UI so no need for localization

2021-02-15 11:19 UTC, czegreanu commented on Incopo/Utils/Constants.swift
> +struct Constants {
don't localize these

2021-02-15 11:19 UTC, czegreanu commented on Incopo/Controller/RegisterViewController.swift
> +        let user = User(email: emailTextField.text ?? "",
i think it's better if you make the fields optional

2021-02-15 14:55 UTC, czegreanu approved these changes

2021-02-16 12:36 UTC, a-nistor commented on Incopo/Controller/RegisterViewController.swift
> +        if firstNameContainsDecimals != nil {
it would be better to directly allow only letters in the text field and ignore everything else

2021-02-16 12:36 UTC, a-nistor commented on Incopo/Controller/RegisterViewController.swift
> +        guard let confirmedPassword = confirmPasswordTextField.text else {
do we want any password validation? min number of characters, require at least one capital letter/special symbol, etc?

2021-02-16 13:15 UTC, merged